image: fedora:latest

before_script:
  - dnf install 'dnf-command(copr)' git libtool make -y
  - dnf copr enable @spice/nightly -y
  - dnf builddep spice -y

makecheck:
  script:
  - ./autogen.sh
  - make
  - make -C server check || (cat server/tests/test-suite.log && exit 1)

statistics:
  script:
  - ./autogen.sh --enable-statistics
  - make
  - make -C server check || (cat server/tests/test-suite.log && exit 1)

syntax-check:
  script:
  - ./autogen.sh
  - make syntax-check
